Zhumanov Yernur 25_2 9

In [2]:
#Problem 1
import numpy as np

def multiply_matrix(A, B):
    return A @ B

def power_matrix(M, n):
    if n == 0:
        return np.array([[1, 0], [0, 1]])
    if n == 1:
        return M
    if n % 2 == 0:
        Half = power_matrix(M, n // 2)
        return multiply_matrix(Half, Half)
    else:
        return multiply_matrix(M, power_matrix(M, n - 1))

def fibonacci_super_fast(n):
    if n <= 1:
        return n
    
    M_correct = np.array([[1, 1], [1, 0]])
    M_n_total = power_matrix(M_correct, n)
    
    initial_vector = np.array([[1], [0]])
    result_vector = M_n_total @ initial_vector
    
    return result_vector[1, 0]

# Example
n_example = 10
fib_result = fibonacci_super_fast(n_example)

print(f"Fibonacci Number F_{n_example}: {fib_result}")

Fibonacci Number F_10: 55


In [3]:
#Problem 2
def knapsack_space_opt(W, weights, values):
    n = len(weights)
    dp = [0] * (W + 1)
    
    for i in range(n):
        weight_i = weights[i]
        value_i = values[i]
        
        for w in range(W, weight_i - 1, -1):
            dp[w] = max(dp[w], dp[w - weight_i] + value_i)
            
    return dp[W]

# Example
W_cap = 50
weights_list = [10, 20, 30]
values_list = [60, 100, 120]
knapsack_max_value = knapsack_space_opt(W_cap, weights_list, values_list)

print(f"Knapsack Max Capacity (W): {W_cap}")
print(f"Max Value with O(W) Space: {knapsack_max_value}")

Knapsack Max Capacity (W): 50
Max Value with O(W) Space: 220


In [4]:
#Problem 3
import numpy as np

def generate_vectors(N, count):
    vectors = np.random.randint(0, 2, size=(count, N))
    return vectors

N_v = 8
COUNT = 3
random_vectors = generate_vectors(N_v, COUNT)

print(f"Generated Vectors (N={N_v}, Count={COUNT}):")
print(random_vectors)

Generated Vectors (N=8, Count=3):
[[0 1 1 0 0 1 1 1]
 [1 0 0 1 0 0 1 0]
 [1 0 0 0 0 0 0 1]]


In [5]:
def jaccard_similarity(x, y):
    x = np.array(x)
    y = np.array(y)
    
    intersection = np.sum(x * y)
    union = np.sum(np.maximum(x, y))
    
    if union == 0:
        return 0.0
    return intersection / union

# Example vectors from Part 1 Output (row 0 and row 1)
x_ex = [1, 0, 0, 1, 1, 0, 1, 0]
y_ex = [0, 1, 1, 0, 1, 1, 0, 0]

jacc_result = jaccard_similarity(x_ex, y_ex)

print(f"Vector x: {x_ex}")
print(f"Vector y: {y_ex}")
print(f"Jaccard Similarity: {jacc_result}")

Vector x: [1, 0, 0, 1, 1, 0, 1, 0]
Vector y: [0, 1, 1, 0, 1, 1, 0, 0]
Jaccard Similarity: 0.14285714285714285


In [6]:
from math import comb

N_sparse = 2000
w_ones = 5

def possible_sparse_vectors(N, w):
    return comb(N, w)

num_vectors = possible_sparse_vectors(N_sparse, w_ones)

print(f"Vector Length (N): {N_sparse}")
print(f"Number of Ones (w): {w_ones}")
print(f"Number of Possible Vectors: {num_vectors}")

Vector Length (N): 2000
Number of Ones (w): 5
Number of Possible Vectors: 265335665000400
